server:
  port: 9090
spring:
  application:
    name: springcloud-oauth-gateway
  #将服务器注册到nacos中
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    ##是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: springcloud-oauth-auth
          uri: lb://springcloud-oauth-auth
          predicates:
            - Path=/auth/**
        - id: springcloud-oauth-resource
          uri: lb://springcloud-oauth-resource
          predicates:
            - Path=/resource/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
  ##这个的意思 是 在spring cloud服务太多的情况下 bean名字重名的情况下多 设置为true 后重名的bean覆盖以前的bean
  main:
    allow-bean-definition-overriding: true
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当nacos中可以找到服务，但是服务连不上时将会重试，如果nacos中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间

##调用方法的超时时间 在调用方配置，被该调用方的所有方法的超时时间都是该值，优先级低于下边的指定配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 6000
